### ISSUE TITLE
List limited range of 675

### ISSUE THREAD

**Issue by matdealm** [waittim/draw_yolo_box#3]
File "draw_box.py", line 111, in <module>
    box_num = draw_box_on_image(image_names[image_total], classes, colors, label_folder, raw_images_folder, save_images_folder)#对图片画框
  File "draw_box.py", line 69, in draw_box_on_image
    plot_one_box([x1,y1,x2,y2], image, color=colors[class_idx], label=classes[class_idx], line_thickness=None)
IndexError: list index out of range

There seems to be a list index issue that limites this to 675 images. Any idea what could fix this?

**Comment by waittim** [comment]
I cannot reproduce this error on my end. I tested a more enormous image volume and it does work with >675 images. 
Probably the error is triggered by some other reason.

**Comment by aditya33agrawal** [comment]
Faced the same issue:

Banana-4_jpg.rf.e7ab025d4785f0ab4ff667d0fe2f3ded
Traceback (most recent call last):
  File "/content/draw-YOLO-box/draw_box.py", line 106, in <module>
    box_num = draw_box_on_image(
  File "/content/draw-YOLO-box/draw_box.py", line 66, in draw_box_on_image
    plot_one_box([x1, y1, x2, y2], image, color=colors[class_idx],
IndexError: list index out of range

I just have 6 images in the dataset.

**Comment by waittim** [comment]
Can you check which list brings the `IndexError: list index out of range` issue? 

It might be caused by `[x1, y1, x2, y2]` which means the annotation information exceeds the image size.

**Comment by matdealm** [comment]
This is closed thanks, it has been solved
